### ISSUE TITLE
遍历输出出错以及最短路径中断运行

### ISSUE THREAD

**Issue by 63243254** [IPreferToEatDinner/Shortest-Way#1]
[CRZ.txt](https://github.com/IPreferToEatDinner/Shortest-Way/files/11521391/CRZ.txt)
[Main1.txt](https://github.com/IPreferToEatDinner/Shortest-Way/files/11521393/Main1.txt)
Timer.txt](https://github.com/IPreferToEatDinner/Shortest-Way/files/11521392/Timer.txt)
前两个是头文件，
在进行DFS时，输出结果只出现了最开始输入的城市，没有遍历城市的输出
另一个问题就是在最后进行最短路径的时候，输入目的地城市之后会卡住不动或者出现一个bug

**Comment by IPreferToEatDinner** [comment]
本问题已在最近稳定版本中得到解决，请fork本项目进行查看
